package uz.pdp.enums;

public enum AdminStatus {
    CLICKED_ADD_PRODUCT,
    SELECT_CATEGORY_FOR_ADD_PRODUCT,
    ENTERED_PRODUCT_NAME,
    ENTERED_PRODUCT_PRICE,

    SEND_PRODUCT_IMAGE,
    COMMIT_OR_ROLLBACK_ADD_PRODUCT,
    ENTERED_PRODUCT_DESCRIPTION,
    DELETE_PRODUCT, UPDATE_NAME_PRODUCT, SWITCH_OFF_PRODUCT, SWITCH_ON_PRODUCT, CHANGE_NAME, CHANGE_NAME_BY_ID, CHANGE_PRICE, CHANGE_PRICE_BY_ID, CHANGE_DESCRIPTION, CHANGE_DESCRIPTION_BY_ID, ENTERED_PRODUCT_QUANTITY, CHANGE_QUANTITY, CHANGE_QUANTITY_BY_ID;
}
